version: '2.4'
services:
    php7-fpm:
        hostname: php7-fpm
        image: php:7.0.1-fpm
        container_name: php7-fpm
        expose:
          - "9000"
        depends_on: 
          - mysql
          
        volumes:
            - .:/var/www/html/openbiblio
      
    mysql:
        hostname: mysql
        image: mysql
        volumes:
          - mysql-data:/var/lib/mysql
        environment: 
          - MYSQL_DATABASE:openbiblio
          - MYSQL_USER:openbiblio
          - MYSQL_PASSWORD:openbiblio
          - MYSQL_ROOT_PASSWORD:root
        ports:
          - 3307:3306
    phpmyadmin:
        image: bitnami/phpmyadmin
        container_name: phpmyadmin
        hostname: phpmyadmin
        depends_on: 
          - mysql
        ports:
          - 8081:80
    nginx:
      image: nginx:latest
      container_name: nginx
      hostname: nginx
      volumes:
            - .:/var/www/html/openbiblio
            - ./openbiblio.dev.conf:/etc/nginx/conf.d/default.conf
      ports:
        - 8080:80
      depends_on: 
        - php7-fpm
      
volumes:
  mysql-data:
