version: '2.4'
services:
    portainer:
        image: portainer/portainer
        hostname: portainer
        container_name: portainer
        restart: always
        ports:
            - 9000:9000
            - 8000:8000
        volumes:
            - portainer_data:/data portainer/portainer
            - /var/run/docker.sock:/var/run/docker.sock

volumes:
    portainer_data:
