 
version: '2.4'

volumes:
    portainer_data:
    
services:
    portainer:
        hostname: 'portainer'
        image: 'portainer/portainer'
        container_name: 'portainer'
        volumes:
            - portainer_data:/data portainer/portainer
            - /var/run/docker.sock:/var/run/docker.sock 
        ports:
            - "9000:9000"
        restart: always
        
        
